"""
Multi-source CVE severity enrichment.

Cross-references NVD and CVEDetails.com CVSS data to produce the most
accurate severity classification. When sources disagree, applies a
deterministic resolution strategy.

Data sources:
  1. NVD (primary)     — CVSS v3.1 from NIST
  2. CVEDetails.com    — aggregated CVSS from multiple vendors
  3. EPSS              — exploit probability (used as tie-breaker)

Usage:
    enricher = CveSeverityEnricher("/path/to/data/cve")
    result = enricher.lookup("CVE-2025-15467")
    # result = {"cvss": 9.8, "severity": "critical", "source": "nvd+cvedetails", ...}
"""

import json
import logging
import os
from typing import Optional

logger = logging.getLogger("vulnscan.cve.enricher")


def _score_to_severity(score: float) -> str:
    """CVSS v3 score to severity label."""
    if score >= 9.0:
        return "critical"
    if score >= 7.0:
        return "high"
    if score >= 4.0:
        return "medium"
    if score > 0.0:
        return "low"
    return "info"


class CveSeverityEnricher:
    """
    Loads CVE data from multiple sources and provides unified severity lookup.
    """

    def __init__(self, data_dir: str):
        self._nvd: dict[str, dict] = {}
        self._cvedetails: dict[str, dict] = {}
        self._epss: dict[str, float] = {}
        self._load(data_dir)

    def _load(self, data_dir: str):
        """Load all available data sources from the data directory."""
        # Load NVD data
        nvd_path = os.path.join(data_dir, "nvd_cpe_cve.json")
        if os.path.exists(nvd_path):
            try:
                with open(nvd_path) as f:
                    for entry in json.load(f):
                        cve_id = entry.get("cve", "")
                        if cve_id:
                            self._nvd[cve_id] = {
                                "cvss": entry.get("cvss"),
                                "severity": entry.get("severity", ""),
                            }
                logger.info("Loaded %d NVD entries", len(self._nvd))
            except Exception as e:
                logger.warning("Failed to load NVD data: %s", e)

        # Load CVEDetails data (generated by cvedetails_fetch.py)
        cvedetails_path = os.path.join(data_dir, "cvedetails_cvss.json")
        if os.path.exists(cvedetails_path):
            try:
                with open(cvedetails_path) as f:
                    self._cvedetails = json.load(f)
                logger.info("Loaded %d CVEDetails entries", len(self._cvedetails))
            except Exception as e:
                logger.warning("Failed to load CVEDetails data: %s", e)
        else:
            logger.info("No CVEDetails cache found at %s (optional)", cvedetails_path)

        # Load EPSS scores
        epss_path = os.path.join(data_dir, "epss.json")
        if os.path.exists(epss_path):
            try:
                with open(epss_path) as f:
                    for entry in json.load(f):
                        cve_id = entry.get("cve", "")
                        if cve_id:
                            self._epss[cve_id] = float(entry.get("epss", 0))
                logger.info("Loaded %d EPSS entries", len(self._epss))
            except Exception as e:
                logger.warning("Failed to load EPSS data: %s", e)

    def lookup(self, cve_id: str) -> Optional[dict]:
        """
        Look up a CVE and return the best severity assessment from all sources.

        Returns:
            {
                "cvss": float,           # Best CVSS score
                "severity": str,         # Derived severity label
                "source": str,           # Which source(s) contributed
                "nvd_cvss": float|None,  # NVD score
                "cvedetails_cvss": float|None,  # CVEDetails score
                "epss": float|None,      # Exploit probability
                "confidence_boost": bool # True if multiple sources agree
            }
            or None if CVE not found in any source.
        """
        if not cve_id or not cve_id.startswith("CVE-"):
            return None

        nvd = self._nvd.get(cve_id)
        cvedetails = self._cvedetails.get(cve_id)
        epss = self._epss.get(cve_id)

        nvd_cvss = nvd["cvss"] if nvd and nvd.get("cvss") is not None else None
        cd_cvss = cvedetails.get("cvss") if cvedetails else None

        # If neither source has this CVE, return None
        if nvd_cvss is None and cd_cvss is None:
            return None

        # Resolution strategy:
        # 1. If both sources have scores, use the HIGHER score
        #    (conservative — assume worst case for security)
        # 2. If only one source has a score, use it
        # 3. EPSS is used as context but doesn't override CVSS
        sources = []
        if nvd_cvss is not None:
            sources.append("nvd")
        if cd_cvss is not None:
            sources.append("cvedetails")

        if nvd_cvss is not None and cd_cvss is not None:
            # Both sources available — take the higher (more conservative)
            best_cvss = max(nvd_cvss, cd_cvss)
            confidence_boost = True  # Multiple sources = higher confidence

            # If there's a major disagreement (>2 points), log it
            if abs(nvd_cvss - cd_cvss) > 2.0:
                logger.warning(
                    "%s: CVSS disagreement — NVD=%.1f, CVEDetails=%.1f (using %.1f)",
                    cve_id, nvd_cvss, cd_cvss, best_cvss,
                )
        elif nvd_cvss is not None:
            best_cvss = nvd_cvss
            confidence_boost = False
        else:
            best_cvss = cd_cvss
            confidence_boost = False

        severity = _score_to_severity(best_cvss)

        # EPSS boost: if exploit probability is high (>0.5), bump severity
        # if it's currently at medium and the CVSS is borderline
        if epss and epss > 0.5 and severity == "medium" and best_cvss >= 6.0:
            severity = "high"
            best_cvss = max(best_cvss, 7.0)
            logger.info(
                "%s: EPSS=%.2f elevated severity medium->high",
                cve_id, epss,
            )

        return {
            "cvss": best_cvss,
            "severity": severity,
            "source": "+".join(sources),
            "nvd_cvss": nvd_cvss,
            "cvedetails_cvss": cd_cvss,
            "epss": epss,
            "confidence_boost": confidence_boost,
        }

    def enrich_finding_cvss(self, cve_id: str, current_cvss: Optional[float]) -> tuple:
        """
        Enrich a finding's CVSS score using multi-source data.

        Args:
            cve_id: The CVE identifier
            current_cvss: The CVSS score currently on the finding (from NVD dataset)

        Returns:
            (best_cvss, confidence_adjustment)
            - best_cvss: The best CVSS score from all sources
            - confidence_adjustment: 1.0 if multiple sources agree, else 0.95
        """
        result = self.lookup(cve_id)
        if result is None:
            return current_cvss, 0.9  # No enrichment data, keep default

        best_cvss = result["cvss"]

        # If we have the same score from multiple sources, boost confidence
        if result["confidence_boost"]:
            return best_cvss, 1.0  # Full confidence when sources agree
        else:
            return best_cvss, 0.95  # Single source, slightly less confident
